project:
  type: website
  output-dir: docs

website:
  title: "Italiaans studeren"
  navbar:
    left:
      - grammatica.qmd
      - zinnen.qmd
      - woorden.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

